SELECT 
    U.USER_ID,
    U.NICKNAME,
    CONCAT_WS(' ', U.CITY, U.STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS('-', SUBSTRING(U.TLNO, 1, 3), SUBSTRING(U.TLNO, 4, 4), SUBSTRING(U.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER AS U
JOIN USED_GOODS_BOARD AS B 
ON U.USER_ID = B.WRITER_ID
GROUP BY 1
HAVING COUNT(1) >= 3
ORDER BY 1 DESC;