a=-int(input())+int(input())
if a>30:print('You are speeding and your fine is $500.')
elif a>20:print('You are speeding and your fine is $270.')
elif a>0:print('You are speeding and your fine is $100.')
else:print('Congratulations, you are within the speed limit!')